-- Mod_GreatPersonIndividuals
-- Author: zheng
-- DateCreated: 11/11/2021 7:26:54 PM
--------------------------------------------------------------
-- 新增若干伟人个体：Liella!唱片
--------------------------------------------------------------
INSERT INTO Types
	(Type, Kind)
VALUES
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD1',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD2',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD3',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD4',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD5',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD6',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD7',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD8',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD9',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD10', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD11', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD12', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD13', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD14', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD15', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD16', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD17', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD18', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD19', 'KIND_GREAT_PERSON_INDIVIDUAL');

INSERT INTO GreatPersonIndividuals
	(GreatPersonIndividualType, Name, GreatPersonClassType, EraType, ActionCharges, Gender)
VALUES
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD1',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD2',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD3',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD4',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD5',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD6',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD7',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD8',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD9',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD10',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD11',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD12',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD13',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD14',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD15',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD16',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD17',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD18',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M'),
	('GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD19',	'LOC_GREAT_PERSON_INDIVIDUAL_LIELLA_RECORD_NAME',	'GREAT_PERSON_CLASS_LIELLA',	'ERA_ATOMIC',	0,	'M');